### ISSUE TITLE
Missing frequency in my country

### ISSUE THREAD

**Issue by kanykeimar** [helium/miner#1021]
Hello, I wanted to set a helium hot spot in my country Kyrgyzstan but it seems like I can not find the frequency code. Can you please help?

**Comment by evanmcc** [comment]
Sorry, @kanykeimar, it seems like Kyrgyzstan does not have an assigned frequency band (according to the LoRa Alliance Regional Parameters Working Group) currently, so we cannot deploy hotspots there at this time.

This thread from The Things Network forum has some interesting discussion, but it looks like there has perhaps been no progress on it since late 2019?
https://www.thethingsnetwork.org/forum/t/frequency-kyrgyzstan/29543
