### ISSUE TITLE
receipt not in order (blockchain_txn_poc_receipts_v1:validate), caused by PR #1026?

### ISSUE THREAD

**Issue by fishpepper** [helium/miner#1072]
I just saw one of those in my miner logfile: receipt not in order
The final result is that the poc is then dropped (PoC receipt submission result {error,{invalid,receipt_not_in_order}}).

Could this be caused by https://github.com/helium/miner/pull/1026?
I am no erlang wiz, but does "receipt not in order" check for consecutive timestamps? 
The PR randomizes the receipts, or do i read it wrong?

**Comment by abhay** [comment]
This report is somewhat old so I'm going to close it for now. Hopefully you've seen some improvement since the more recent releases. Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
