### ISSUE TITLE
Hotspot witnessing less/ignoring beacons

### ISSUE THREAD

**Issue by kd7csy** [helium/miner#1087]
Other Hotspot beacons, gets 4 witness's, hotspots that have witnessed continually in the past and in range just sit "idling" with zero POC traffic. "Idling" hotspot is online, gets 20+ in discovery mode. Gets 10 witness with all beacons. 

Hotspot example is: Dazzling Wintergreen Huskie

Experiences up to 12 hours of zero POC activity. 
Confirmed by tech support to be functioning properly

**Comment by b-effect** [comment]
same problem

**Comment by abhay** [comment]
This report is somewhat old so I'm going to close it for now. Hopefully you've seen some improvement since the more recent releases. Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
