### ISSUE TITLE
Certain Challengers seem to be associated with 0 witnesses to any beaconer they challenge

### ISSUE THREAD

**Issue by Troposphericduct** [helium/miner#1089]
My Miner usually gets at least 10 witnesses, now maybe more- hard to tell, Over the past 3 days there have been challengers to my miner where I receive no apparent witnesses.
  The most recent challenger to my miner was Joyous Emerald Pelican at 0811AM, 25 Sept. 2021. In viewing Pelican's activities you need to go back 15 challenges before you will find a witness to a beacon via one of Pelican's challenges.
   20 minutes after my last 0 witness response to my miner's beacon I ran Discovery which had 84 unique miners respond to the discovery so I believe my miner's TX is OK.
  Pelican seems to be having a lot of witnessing going on which maybe impacts Pelican's ability to collate/randomize responses to the Beaconers Pelican challenges, perhaps?
    I'll continue to investigate the challengers when I do not receive witnesses to see if their other challenged beaconers receive witnesses also.

**Comment by abhay** [comment]
This report is somewhat old so I'm going to close it for now. Hopefully you've seen some improvement since the more recent releases. Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
