### ISSUE TITLE
Almost zero witnessed beacon events

### ISSUE THREAD

**Issue by Hmpflala** [helium/miner#1091]
Since around september 22nd I am receiving almost 0 earnings and barely any "witnessed beacon" events. 

**Other events**
"Sent beacon"-events: Receiving 10 witnesses most of the time
"Challenged beaconer"-events: 0 witnesses since september 23rd

According to hotspotty:
Valid witnessess as a transmitter: 67
Valid witnesses as a witness: 3

Link to hotspot: https://explorer.helium.com/hotspots/11598CNcAFNcKgB3GUCDaUXdZnuqEGtVXn7YU8tRMfnhYvmuzph
Hotspot: Sensecap EU

**Comment by mibsmibs** [comment]
Same but totally 0 witnessing.
![10_1](https://user-images.githubusercontent.com/85662068/135611275-5343870b-ced8-4c05-ad4b-2a2cd7aae0fd.png)

**Comment by axkman** [comment]
Same problem here, zero beacons sent.
Witnessing other hotspots is also dropping down, like the other hotspots used to be witnessed by my hotspot are sending less beacons aswell.

**Comment by b-effect** [comment]
Same problem
bobcat 868
since 5 days

**Comment by Ivayloooo** [comment]
since two days ago, the same here, start dropping down the witnesses and not witnessing anything or finding witnesses

https://explorer.helium.com/hotspots/11aA2Y3PRJcxcasL1tm3R3eDrbmjVFhdr2GqjobcaS4vsXQv9j2

**Comment by abhay** [comment]
This report is somewhat old so I'm going to close it for now. Hopefully you've seen some improvement since the more recent releases. Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
