### ISSUE TITLE
Witness Invalid Issue

### ISSUE THREAD

**Issue by inforkill** [helium/miner#1108]
Hi, recently I'm getting multiple witness invalid and missing out on rewards with a miner that is present in the adjacent hex and is 850 m away. Please look into it and let me know what is going wrong.

Only change I made is setup my antenna outside of my window.

My miner name: basic Rainbow Wallaby

Witness Miner: Bumpy Watermelon Frog

Attached screenshots.
<img width="370" alt="Screenshot 2021-10-03 at 12 28 00" src="https://user-images.githubusercontent.com/91827311/135749705-8c3efc23-d979-46e4-98b0-a0405d90eaa6.png">
<img width="475" alt="Screenshot 2021-10-03 at 12 28 15" src="https://user-images.githubusercontent.com/91827311/135749708-6b27ef8a-2e8e-4d60-8045-fe96459c285c.png">
<img width="458" alt="Screenshot 2021-10-03 at 12 28 33" src="https://user-images.githubusercontent.com/91827311/135749709-1a9755d3-9f58-4000-8497-1edcedeea87a.png">
<img width="350" alt="Screenshot 2021-10-03 at 12 28 48" src="https://user-images.githubusercontent.com/91827311/135749712-39f6c735-a2e4-42c1-9ec8-e97967e6a652.png">

**Comment by abhay** [comment]
This report is somewhat old so I'm going to close it for now. Hopefully you've seen some improvement since the more recent releases. Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
