### ISSUE TITLE
Hotspot not sending any beacons and showing offline regularly in app and on explorer while being online.

### ISSUE THREAD

**Issue by axkman** [helium/miner#1109]
Since 23 september my hotspot is not sending beacons. However the internet connection is perfectly fine, port 44158 opened, tested and checked out 100% okay. No internet downtimes, no problems with firewall etc. IP adress of hotspot on LAN is static and WAN IP is static too.
Hotspot is shown as offline often in Helium app and in explorer site, while being actually being online - peerping etc towards the hotspot also works. Checking if the poort is open etc also checks hotspot is online on the internet and poort 44158 is open.
Also, it looks like the amount of witnessing of other hotspots in its surrounding is also dropping down. As if they beacon less often too?

Hotspot is a Sensecap EU.

**Comment by abhay** [comment]
This report is somewhat old so I'm going to close it for now. Hopefully you've seen some improvement since the more recent releases. Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
