### ISSUE TITLE
Rak2 hasn’t send any beacon over 30 days

### ISSUE THREAD

**Issue by Dachux60000** [helium/miner#1113]
The hotspot and router has been rebooted many times
It has PW set up 
It witnesses other hotspot beacons multiple times a day

**Comment by abhay** [comment]
This report is somewhat old so I'm going to close it for now. Hopefully you've seen some improvement since the more recent releases. Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
