### ISSUE TITLE
miner

### ISSUE THREAD

**Issue by MisterMazair** [helium/miner#1122]
Hi.
In my country, the frequency plan is 433 EU,
if I buy a miner with support for the EU 868 frequency plan, will it work and mine cryptocurrency?

**Comment by shawaj** [comment]
> I can't understand why, is it because in my country it is allowed in this frequency plan or because another frequency plan is not supported?

It is because the hardware for EU868 (the LoRa concentrator) is different to the hardware for EU433. One is 868 MHz and the other is 433 MHz.

What country are you in?

**Comment by MisterMazair** [comment]
I am in Azerbaijan, this is the first euro zone with a 433 frequency plan

вс, 10 окт. 2021 г. в 22:01, Aaron Shaw ***@***.***>:

**Comment by ke6jjj** [comment]
Has your question been answered?

**Comment by MisterMazair** [comment]
No, not yet.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

чт, 25 нояб. 2021 г. в 00:13, Jeremy Cooper ***@***.***>:

**Comment by abhay** [comment]
Unfortunately this issue cannot be resolved in this repository. If you feel that the on-chain frequency plan isn't correct for your region, you'll need to connect with the LoRaWAN committee of the DeWi and they will have to work through their process to confirm the regional parameters. They will initiate the chain variable change that is required to update this going forward since it's not configured on the miner codebase.
