### ISSUE TITLE
beacon/witness pattern: can witness fine until a beacon is sent

### ISSUE THREAD

**Issue by bobcatminer-admin** [helium/miner#1133]
We're seeing several such cases that, where users have realized that they can witness fine until the hotspot beacons, which always results in 0 witness and that also stops the hotspot from witnessing. The pattern has been summarized as:

1. hotspot witnesses other beacons
2. hotspot sends own beacons
3. hotspot own beacon returns 0
4. hotspot stops witnessing

Some users have found this pattern and began regularly rebooting the hotspot after step 3, so that once the hotspot is rebooted, it starts this cycle again until step 4, when users reboot it again.

**Comment by SteveisIT** [comment]
Issue exists across SB and Sensecap units as well.

**Comment by abhay** [comment]
This report is somewhat old so I'm going to close it for now. Hopefully you've seen some improvement since the more recent releases. Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
