### ISSUE TITLE
0 witness miner 

### ISSUE THREAD

**Issue by Karnage1Reaver** [helium/miner#1137]
My miner GENTLE MANGO BABOON was operating correctly until 48 hours ago and now every time it sends out a beacon no one is able to witness. I have restarted and rebooted the device and have checked over my internet settings and have set up the correct port forwarding settings. It is also connected via Ethernet cable.

**Comment by Karnage1Reaver** [comment]
The same issue has arises again and worse this time as it has  gone on for longer.

**Comment by abhay** [comment]
This report is somewhat old so I'm going to close it for now. Hopefully you've seen some improvement since the more recent releases. Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
