### ISSUE TITLE
BUG Fix: Listen IP Address vs API Reported Address, one of them works, other does not.  Provide fix to use the correct IP.

### ISSUE THREAD

**Issue by bitlite** [helium/miner#1175]
Hello support team,

I would like to report some issues with some miners.  Due to IPTV and IP Phone services, Providers are offering multiple IP Addresses for Home services.  Due to this, they are also reporting different IP Addresses vs the ones that are actually visible via the normal connection and reported by the public IP address.  

I have found some Internet providers are port forwarding port 44158 of the Public Internet IP Address to their TV/Phone IP Address and therefore causing a relayed effect that is not fixable by the helium owner.  When we check the info at app.heliumstatus.io we see 2 different IP Addresses (Listened = TV/Phone IP and Forwarding is block, API Reported is the actual IP that is the Internet traffic and Port is OPENED.

I would like to add a feature that would scan both Listened and API reported addresses.  If the Listen and API address are not the same, the service will then test both IP addresses delivered and then determine which one has the appropriate port forwarding setup properly.  Once detected, update the miner to report the correct IP address to connect to.  Also, enforce the P2P to reconnect to the correct IP address of the miner.

This may cause a small bump in Internet traffic but it will provide a solution for those whose miners are losing HNT due to providers using multiple IP Addresses and poor Network configurations on the ISP side.

This issue came to light when my friend has the same issue.  He has IPTV and Phone services with his provider.  The Listened IP ended up being his IPTV IP Address and the API reported address was his real IP for Internet traffic.  Since the IPTV was not forwarding traffic to his real IP Address due to the forwarding not implemented on the ISP provided IP for IPTV, my friend could not make those changes within his router.  Only the ISP, which will NOT perform the function, can make those changes.  

You can see the following example as well. This user is an 4G LTE user which also has 2 different IP Addresses reported.
![image](https://user-images.githubusercontent.com/4667628/140792151-16536bee-188e-431a-8339-7a54f6e312cc.png)

In the end, the backend should detect which IP address is the correct one and use the correct IP Address to communicate over the Helium P2P network.

**Comment by Biotonnne** [comment]
Thank you for this!!

Did your friend sort this out with his ISP? I think many users do face the same problem (I do with 2 miners). Could this also be an explanation for different relay states with different API Providers in the App? Mine show unrelayed when using the Stake Joy Provider but relayed when using Helium API.

https://explorer.helium.com/hotspots/112gBqmyByMYL1hvgRggiePVuTR4kcVDHkcG7WxSo175zq5cB1db
 and
https://explorer.helium.com/hotspots/11nDx4BH4CQpPKMsyMTSRr2yESdCs5m7ida8dTDYL8LP2epSTiV

**Comment by RPCrypto** [comment]
![github_Observed_vs_API_Reported___Listen_Address](https://user-images.githubusercontent.com/94377136/141796879-157b4732-b6a3-4a11-9385-ebaa6de326db.jpg)

I have a similar situation where even the listening port is off ...

**Comment by bitlite** [comment]
@Biotonnne : The problem my friend has is with his ISP provided router.  it seems buggy and ends up mixing streams between the Internet and IPTV data.  This is why he ends up losing his Hotspots once in a blue moon.  I informed him to put that piece of crap into bridge mode and put a real router (Asus RT-AC68U or greater) right after that buggy unit but he will have problems with his IPTV service.

Some people just can't win due to their provider's push to use their equipment.

@RPCrypto : I tried your Observed Listen address and got this
![image](https://user-images.githubusercontent.com/4667628/141879680-e472693e-e9e0-45e1-a65c-2f585ef2df22.png)

So it seems to be working... are you still offline?  Also, what program is changing that listen port to 26270?

**Comment by RPCrypto** [comment]
I am apparently online - and earn some minimal HNT ... well, at least I was before this total Helium blockchain halt / meltdown :-)
I don't have IPTV, my ISP does not offer IPTV and I don't use any program (that I know of) that requires that other port.
My Bobcat was transferred from another owner, though that was some weeks ago ...

**Comment by FiloFilo1984** [comment]
Like THOUSANDS OF OTHERS, may you have the problem that your hardware get a issue suddenly with no reason OR your antenna has been walking from it's place. You have to be carefull, the helium network is full of miracles, unusual things happen for many THOUSANDS HOTPOT OWNERS ALWAYS AT THE SAME TIME

**Comment by bitlite** [comment]
> Like THOUSANDS OF OTHERS, may you have the problem that your hardware get a issue suddenly with no reason OR your antenna has been walking from it's place. You have to be carefull, the helium network is full of miracles, unusual things happen for many THOUSANDS HOTPOT OWNERS ALWAYS AT THE SAME TIME

Then, since you bought a hotspot from a manufacturer, please contact your MANUFACTURER FIRST for support.  Helium is not a Hardware debugger.  Any hardware related issues MUST go through your hardware vendor.  

You are talking like going to McDonalds and asking for a Whopper.  It is a hamburger but only a different flavour.  McDonalds will not have the knowledge on how to make a Whopper.  Whoppers are made by Burger King along with their secret spices... Same goes with Helium hardware.  Each manufacturer has their own secret sauces.  Try them first.

Anyways, I think this thread will be ignored as this issue may no longer plague us after Q1 2022 with Light Hotspots in play.

**Comment by benkej05** [comment]
Any workaround? I have only one valid ip and the miner reporting old one for the blockchain before I changed reboot the whole system

**Comment by RPCrypto** [comment]
No workaround really. I just gave it time. The problem went away in about 10-15 days. If your "observed listen address" in heliumstatus.io is OK you are probably good.

**Comment by akriv-git** [comment]
I have a RAK v2 miner, set it up at home for 3-4 days.  It took a day for it to start witnessing, but was running well.  I moved it to a new (hopefully better?) location yesterday.  A few things I’ve done differently:
(1) host is using an xfinity router.  While I have xfinity at home as well, it’s my own router.
(2) I connected the miner BEFORE setting up port forwarding.
(3) I used an Ethernet cable instead of Wi-Fi. wifi was what I used at my home.  The device remembered my IP from home.  Even though it was on Ethernet, I had to configure Wi-Fi so it would ‘forget’ my previous Wi-Fi config.  After doing this, I got out of relay mode.  But the Helium API Address Listener is still my old IP.  

The miner is not able to witness or send beacons.  Just challenges.  
I tried restarting today, leaving the miner off for about 5-10 mins.  Didn’t work.
I don’t really like the idea of waiting 10-15 days for it to “fix itself”.   That seems a ridiculously long time, and makes me think it fixes itself when a firmware upgrade is pushed.  That’s the only thing I can think of that would change after an extended time and have the possibility of clearing the setting.  

The location is remote.  I plan to go there in a couple days to tinker with it.  I’m going to try disconnecting Ethernet and just doing Wi-Fi and/or simply resetting the network config, if I can.  I wish RAK v2 had remote management.

**Comment by ionpozitiv** [comment]
I have the same problem with my Finestra Miner. Their support sent me some vague instructions on how to fix it, but that didn't work... I am also getting reduced earning, miner shows unreachable in Helium Geek because it tries to ping the old IP...

"We would like you to reconnect your FinestraMiner with the Finestra Diagnostics App. 
In order to do that, please choose another WIFI option from the list and immediately cut the connection. 
After you do that please reconnect to your network once again. Please observe the IP address and let us know if you witness a change.
-Team Mimiq"

**Comment by akriv-git** [comment]
Quick update:  Maybe it will help @ionpozitiv and others.  
I got access to the remote location last night to tinker with the miner to see if I could improve things.  The reason for the move from a sparsely populated area to an area with a lot more green hexes on the explorer was that I expected a lot more activity immediately.  Maybe this was a faulty assumption.  When I thought it wasn't fully working (beaconing/witnessing) , the miner did send out one beacon in the previous 24 hrs.  That suggested it _must_ be working.  But, as stated, I expected a lot more witnessing, and I got none.

So, I tinkered with the network configuration.  Switched from ethernet cable to WiFi.  On the RAK v2, changing the network WiFi config prompts you to forget the previous network config.  So, I opted for YES.  Xfinity re-assigned my IP at that point, which broke my port forwarding, but once I re-configured everything, the hotspot was reported online by heliumstatus.io.  Still, the old address for API listener address.  👎  So, no effective change from before with the ethernet cable.  I did also enable the DMZ option for the IP of the hotspot on the crappy Xfinity router, but I didn't notice anything from that, since I already had port forwarding configured for 44158.

With nothing left to try, I just left it online.  Overnight, it sent two beacons and had one witness transaction.  I checked heliumstatus.io and the API listener address hasn't changed, and is still stale.  So, basically, my conclusion is that the stale data for API listener address has nothing to do with miner operation.

**Comment by alessiofx** [comment]
> ![github_Observed_vs_API_Reported___Listen_Address](https://user-images.githubusercontent.com/94377136/141796879-157b4732-b6a3-4a11-9385-ebaa6de326db.jpg)
> 
> 
> 
> I have a similar situation where even the listening port is off ...

What is this site?

**Comment by RPCrypto** [comment]
I think it is heliumstatus.io which went from free to payed service to offline
Regarding the situation ... If your hotspot was moved from a place to another, it may take even two weeks before the API pics up the (IP) changes ...
If otherwise it is working, just let it be.
Alternatively you can try a realtime check on the hotspotty app/site ... but you have to be "not relayed" for that to work ...
Hope this helps!
Good luck!


Sent from Yahoo Mail on Android 
 
  On Fri, Jun 10, 2022 at 0:00, Alessio ***@***.***> wrote:   





I have a similar situation where even the listening port is off ...


What is this site?
