### ISSUE TITLE
Miner doesn't send beacons (not relayed for sure)

### ISSUE THREAD

**Issue by Ahmetarlanoglu** [helium/miner#1197]
Even though my challenged hotspots witnessed by other hotspots (which proves my miner isn't relayed) my miner doesn't send any beacon signals. Name ;C
![Screenshot_20211111-130900_Chrome](https://user-images.githubusercontent.com/94110583/141279672-191515ef-23e9-42ae-8fd3-2894d05ee0a5.jpg)
heesy Rouge Condor

**Comment by b-effect** [comment]
I have same issue both of my miners

**Comment by gusosborne** [comment]
Same here, both RAK miners (both on 1Gb fiber with dedicated public IPs, both using quality aftermarket antennas and LMR-400, one @80m and the other @15m AGL. started 6 days ago. 
Tons of reports ever since the bad PoC variable/ rollback. Beacons seem to be about 1/10th of normal. I believe it is related to this:

https://github.com/helium/miner/issues/1174

**Comment by abhay** [comment]
Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
