### ISSUE TITLE
13 days 0 witnesses

### ISSUE THREAD

**Issue by efe92** [helium/miner#1217]
![wt](https://user-images.githubusercontent.com/33613610/142235294-f6eb7843-962e-410b-a24a-d1ef0d6da6e6.png)
almost 13 days. i just change my antenna. why is that happened?

**Comment by Harv2021** [comment]
![image](https://user-images.githubusercontent.com/94573259/142291411-5c24df95-3f65-4804-b357-98c0807f5bdc.png)

Same issue here with Sensecap. I have an outdoor 5.8 dBi antenna on rooftop, LMR400 cable, not relayed, in major city, fast internet connection....and ever since the late October - Early November firmware updates my hotspot beacons has crashed significantly. I recently went 7 days without witnessing anything...then randomly witnessed like 8 beacons in one day....

I've triple checked my wires and antenna, replaced/upgraded SD card....What can possibly explain the massive drop off in witnessing and being witnessed?  I am well aware that earnings fluctuate...but a 53% drop in 30 days?

Docile Clay Wolverine

**Comment by ElYoM** [comment]
Many of us are in the same case, some for longer than others (my 3 hotspots suddenly stopped mining simultaneously since October 27th, see here: https://github.com/helium/miner/issues/1205).

22 days later, no help on this subject either from Helium or the manufacturer. Good luck...

**Comment by Harv2021** [comment]
My hotspot seems to be working again....woke up and witnessed like 12 or so different beacons. Hopefully this keeps up because last time I had a good day it Flatlined for several days afterwards.

**Comment by kukoc63** [comment]
Flatline is back on my rak

Not a single change in the organisation --> 1witness / day max   + 0 beacon  (i don't talk about the halted blockchain) since october 28th
![Sans titre](https://user-images.githubusercontent.com/94638212/142470182-b2645bc7-6a0e-4655-95cd-3c9bbbe325e7.jpg)
k 

My other rak and my bobcat works perfectly in the same city...

**Comment by abhay** [comment]
Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
