### ISSUE TITLE
Miner stuck syncing for 7 days

### ISSUE THREAD

**Issue by willpop2** [helium/miner#1254]
Hello, I was directed to post here from the Discord. I have a Rak2 Miner from CalChip that has been working just fine since I received and set it up back in June. In the last week, it has stopped earning completely and is stuck syncing. I have not witnesses a beacon or transferred data packets in 8 days now. I know there have been issues with the network lately, but from what I have seen, others are not experiencing an issue like this (they are getting lesser or sporadic earnings, not stuck). Any ideas? Is there something I can do on my end to correct this?

**Comment by freefall-git** [comment]
I have had a similar problem with RAK ​​v2 for 6 days now. Before that, RAK worked perfectly for about a month. 

I waited 3 days, and since the activity was still 0, I changed the height of the antenna (for 1 m). 36 hours have passed since then. On https://www.heliumtracker.io/ it says synchronization Blockchain - almost synchronized - last update: 3 days ago, but in the web application it says Synchronization is 100% (every 60 min I watched the number of blocks decrease and in the end I got the information that the synchronization was completed 100%). However, 'Syncing' was still written in the Web application, and Activity and Earnining have been zero for 6 days.

All the time, for 6 days now, the synchronization is close to 100%, but not exactly 100% ...
It was 99.95, then 99.90, ... I am now at 99.3%.

All the time my HS is at block height 1101609! HS seems to be stuck in a loop and never comes out of the loop ...

For all this time, due to system problems helium has released 4-5 firmware updates. my RAK HS downloaded all the update within 1h of the release and I currently have version 2021.11.21.2.

I tried to find the answer on the discord, I wrote to support@helium.com, but I didn't get help. I hope someone who knows what this is about will come forward. thanks in advance.

![Screenshot 2021-11-24 031415](https://user-images.githubusercontent.com/94942797/143159427-90172e96-f4d4-4076-80ba-566c5f9764dd.jpg)

![Img 2](https://user-images.githubusercontent.com/94942797/143159442-352f9b71-dd28-4147-ba12-13c75ca65035.png)

![HS-block problem-2](https://user-images.githubusercontent.com/94942797/143159503-040db0dc-3275-4e58-8039-26509d7f87fc.png)

**Comment by willpop2** [comment]
It didn't occur to me to try to run diagnostics, and when I try to scan it is not finding my hotspot... maybe this is part of the problem? Very annoying to be encountering this issue all of a sudden. I will try the help email as well.

**Comment by C4ngr3j0** [comment]
I am having a similar issue. I don't see almost any activity in the last 9 days
![image](https://user-images.githubusercontent.com/90414120/143289267-4e7c7e80-ae57-4096-841c-6587ea518579.png)

**Comment by Dam63** [comment]
Similar for me at block **110534** on Nebra.
I can see on the network monitor that miner is non stop loop downloading something.
![Capture](https://user-images.githubusercontent.com/2207605/143308302-d82af670-31fc-434e-9452-d0485c7dd7ae.JPG)

**Comment by chrisdaid** [comment]
For me I have a Nebra stuck on block 1046852. No update, still on firmware 9/27 and connected with ethernet.

**Comment by chrisdaid** [comment]
> Similar for me at block **110534** on Nebra. I can see on the network monitor that miner is non stop loop downloading something. ![Capture](https://user-images.githubusercontent.com/2207605/143308302-d82af670-31fc-434e-9452-d0485c7dd7ae.JPG)

How do you check with network monitor? For me I have a netgear nighthawk router and I can't seem to find a network monitor.

**Comment by Dam63** [comment]
@chrisdaid it was Freebox (French provider box) that provide this data.
No more problem since few hours after a stop (30 min), a blacklist of the wifi mac address on the internet box. I am now 100% RJ45 and sync

**Comment by willpop2** [comment]
@Dam63 you fixed the issue? Can you provide an explanation for a less savvy person like myself of how to attempt a fix? I am still stuck, Discord had not been helpful (one person suggested I need to replace the memory card perhaps?) and I have heard nothing from anyone at Helium Support.

**Comment by C4ngr3j0** [comment]
@Dam63 @willpop2 yeah, please tell us D:

**Comment by Dam63** [comment]
I have just unplug power for 30 min, blacklist the wifi MAC address of the miner on the internet box to avoid wifi connection and to be sure to use 100% RJ45

**Comment by connor-hollenbeck** [comment]
Another data point: My OG Helium spot has same issue. Been "Syncing" now for the last 8 days. Hotspot name "Small Hotpink Goat". Connected via ethernet, 200 Mbps connection and hotspot is sending quite a bit of data. My neighbor, Decent Corduroy Chicken (who also has an OG Helium spot) has also been stuck at "Syncing" for the same amount of time.

**Comment by StoneLionCrypto** [comment]
I have the same issue here.  Odd thing, it only happened to one of my 3 Rak V2 hotspots.  Also, the port it is looking for now is 44159.  It was 44158 from the beginning so not sure why that changed.  Anyone else notice the port issue?  Says I am online and syncing but have not made any progress on block height in 7 days.

**Comment by abhay** [comment]
Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
