### ISSUE TITLE
Activity drop bij 90%

### ISSUE THREAD

**Issue by Davekted** [helium/miner#1274]
Hey all,

Unf the last update didnt fixed my p2p issue with my miner.

Not a dupe of problem #1205
@amirhaleem still no difference.

![image](https://user-images.githubusercontent.com/95023956/144561040-b142d7f6-22c5-4ff6-8f3a-36e470f5084e.png)
![image](https://user-images.githubusercontent.com/95023956/144561072-be9862dc-b9a9-4e41-b318-731543ff3dc7.png)
![image](https://user-images.githubusercontent.com/95023956/144561440-bb46a404-1560-493a-8934-1cf85d0d5e61.png)

_Originally posted by @Davekted in https://github.com/helium/miner/issues/1259#issuecomment-985273475_

**Comment by yogeshnichal** [comment]
I have 7 miners they  earn only 0.03 HNT per day since last week. They were working fine before, It's outdoor setup, Public/static IP on 4G LTE.
I am trying to set up an IoT network for my small town so I have all my miners setup close to each other.
https://explorer.helium.com/accounts/13wvymwxsxw6nDbRa5uE5wm76cyDgM1KNKtJVmnXbzd1tmRbQuA
![Shot 0173](https://user-images.githubusercontent.com/56922233/144584530-478380e2-3d4b-4e92-a6a7-44aadd8e4673.png)

**Comment by abhay** [comment]
Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
