### ISSUE TITLE
miner dosent send any bicon for 4 days now

### ISSUE THREAD

**Issue by tzacha** [helium/miner#1309]
my mntd miner dosent send ant becon for already 4 days...
it was working just fine untill now and its not relayed...
helium://hotspot/112MsjsixNNkzWqe19f5bQLocdPZKWHYAoP5nwqPnqYUFqNMjufz

**Comment by shawaj** [comment]
Looks fine? https://explorer.helium.com/hotspots/112MsjsixNNkzWqe19f5bQLocdPZKWHYAoP5nwqPnqYUFqNMjufz/activity

**Comment by tzacha** [comment]
now its back

thanks
tzach

בתאריך יום ג׳, 21 בדצמ׳ 2021, 01:01, מאת Aaron Shaw ‏<
***@***.***>:

**Comment by marc88-crypto** [comment]
Same thing here :-(

https://explorer.helium.com/hotspots/112hREceKfsnwr557Bgx47BZuWC3RujGDFccd1ZxiMs1zH2B8iiP

**Comment by shawaj** [comment]
> Same thing here, already for 7 days In a row👎
> 
> https://explorer.helium.com/hotspots/112hREceKfsnwr557Bgx47BZuWC3RujGDFccd1ZxiMs1zH2B8iiP

@marc88-crypto yours is actually a nebra so i can take a look at it...which I have just done...i think possibly the issue is that you are connected to both WiFi and ethernet and you have a fixed IP on the LAN of 10.0.1.170 for both connections - so you have an IP address conflict

I think if you remove WiFi and just use ethernet, or alternatively have WiFi and ethernet on separate internal IP addresses then this will fix the no beacons

**Comment by marc88-crypto** [comment]
@shawaj your a legend! Thanks!

**Comment by vanjulio** [comment]
rak v2 on its 9th day of no beacons.  stopped after 12/14/2021 firmware upgrade.  coincidentally I installed a new antenna cable same night. but has finally made the first witness ... steadily issuing, but not responding to any challenges?  https://explorer.helium.com/hotspots/112qJdvFR7MgttNLCmNjCeVw6VTxM8c3KK2SZKtQkEPkD4xB9imk

**Comment by vanjulio** [comment]
> rak v2 on its 9th day of no beacons. stopped after 12/14/2021 firmware upgrade. coincidentally I installed a new antenna cable same night. but has finally made the first witness ... steadily issuing, but not responding to any challenges? https://explorer.helium.com/hotspots/112qJdvFR7MgttNLCmNjCeVw6VTxM8c3KK2SZKtQkEPkD4xB9imk

OK after 9 days now magically it just sent beacon and I got my first witness since coming online October 29th!  PARTY TIME!

**Comment by shawaj** [comment]
> @shawaj your a legend! Thanks!

No problem! Looks like it's beaconed now which is great 👌

**Comment by yooitsgreg** [comment]
Same issue here: https://explorer.helium.com/hotspots/112eWyTrhGz6qYM7YSRGvmC1aeW7QUdfVeXALDiGMwCX9sn8c1gp/activity

Hasn't sent beacon in 5 days and has significantly less challenges than my other hotspot setups. In Explorer under "All Activity" I see lots of "Created Challenge" entries but rarely a corresponding "Challenged Beaconer" entry. Seems to be issue with p2p network dropping challenge packet. Maybe this is also why I am not getting Challenges/Sending beacons. I know this isn't due to challenged hotspot being relayed because it is too consistent for the hotspot above and works so consistently for other hotspots. Any advice on what's going on / how to debug?

**Comment by tareqaldaher** [comment]
Hello, my miner didn't sent a beacon since a month, and now I'm 0 on witnesses, can you help me please? 
https://explorer.helium.com/hotspots/11QEafhtB27ykgEgNBmJCGjnnmoE5gxXwWzEitgZLKMxHwxpos3

Best regards

**Comment by knjizar** [comment]
Same here https://explorer.helium.com/hotspots/11bKZ6JuCwtdd3m93pjbMpJpzYS25rmsUvaj1TSUQEAJYC6QK1f
Is there any solution for that?

**Comment by meowshka** [comment]
Please make sure you have the latest firmware installed on your hotspots and if there are still any issues, contact the manufacturers directly.
