### ISSUE TITLE
hotspot-app doesn't support jsonrpc add_gateway_txn/2 output

### ISSUE THREAD

**Issue by encku** [helium/miner#1365]
add_gateway_txn/2 is works json rpc returns txn but hotspot app doesn't support this output.

_Originally posted by @encku in https://github.com/helium/miner/issues/1118#issuecomment-1014892807_

**Comment by ke6jjj** [comment]
@encku can you provide more error logs or information? You mention the hotspot app, but you've tagged the miner. I know they're both involved, but we need to narrow down which component is having the issue.

In your response, can you attach the transaction output from the miner so that we can inspect its contents?

**Comment by encku** [comment]
I think don't need output the other issues also explain why hotspot app can't handle the output :)
