### ISSUE TITLE
Rak - No inbound/outbound/block-height 1, after 01/12/22 OTA

### ISSUE THREAD

**Issue by m1xmstr** [helium/miner#1366]
This issue is just like the issue we saw 01/04 

Miner went offline and after 3 days then lost the ability to ping and reach port 44158

RAK miners affected: MNTD and CalChip

Miner has been plugged into ethernet and powered on.

Static IP and Port Forwarding were setup ~ Miner was working 100% for a full week before it flatlined again.

Some users have reported the following:
![image](https://user-images.githubusercontent.com/4117245/150022228-c854d481-e8b5-49be-966f-b0d4d5c2f025.png)
![image](https://user-images.githubusercontent.com/4117245/150022252-ba21b58a-db46-4481-9cc4-23a81f995d4c.png)

**Comment by m1xmstr** [comment]
While waiting for my CalChip RAK v2 I noticed the issues reported on 01/04

I ordered a Samsung Pro Blue 128GB sd card and flashed it based on this article: https://support.getmntd.com/hc/en-us/articles/4418137820951-I-need-to-replace-the-microSD-card-on-my-hotspot

My RAK (brand new never powered on) when it arrived was swapped with the flashed Samsung SD card.  Powered on it sync'd in about 2-3 hours according to the Bluetooth diagnostic report.

This miner was installed and was fully operational and mining fine for a week.  Then around 01/14 the miner went to an offline status.  The miner was pinging and could use port checker to the public IP for 44158.

Then on 01/16 the miner stopped responding to pings and the port appears to be closed; as if it is powered off or the OS is completely hung.

Many other RAK users are also experiencing this in the RAKstars official discord channel.

**Comment by cuteogre** [comment]
I concur with this, have almost the same problem with block height of 1 for 5 days now (since the last update last Jan 12th).

I did a backup image of the SD card around Jan 18th, mounted it on a linux system, and analyzed it and found some interesting things that may help debug this issue:

- The data directly containing the various rocksdb files are mostly empty of data. ledger.db does have some configuration items but blockchain.db SST files have almost nothing in them
- There are several messages about a canary (some sort of watchdog server?) in the logs like:

> Jan 16 10:50:55 Helium-Hotspot user.notice root: [canary] stopping miner: block age was 1642329953
> Jan 16 10:51:11 Helium-Hotspot user.notice miner[14710]: Starting up
> Jan 16 11:47:17 Helium-Hotspot user.notice root: [canary] stopping miner: block age was 1642333335
> Jan 16 11:47:36 Helium-Hotspot user.notice miner[28179]: Starting up
> Jan 16 12:39:05 Helium-Hotspot user.notice root: [canary] stopping miner: block age was 1642336443
> Jan 16 12:39:21 Helium-Hotspot user.notice miner[6397]: Starting up

These logs come out about every 45 minutes and block age certainly is suspect!  Block age is supposed to be the # of seconds between the current time and the last block in the blockchain (to check if the miner is synced or not). That value in seconds is about 52 years! .. and keeps incrementing approximately the every 45-50 minutes...

Looks like because of that super large block age, the miner doesn't do anything and it keeps getting restarted by the canary process - so it basically does no mining the whole time!

I don't know the root cause of this as I don't have a running system but I hope this helps the devs focus on this problem and hopefully find a solution!

**Comment by m1xmstr** [comment]
A power cycle brought my miner back online and all is functioning for me.

Others are still having issues regarding this.

**Comment by cuteogre** [comment]
Yes, I am still having the same issue.. Power cycled around 3 times the past 6 days.. still flatlined even though it's online/pingable. Height is still 1 even today based on API info updated today (1/19/2022).

Is there any way to just zap the current database on the SD card and let it start from the beginning? I'd rather do that and wait but at least see some progress rather than waiting for the block height of 1 that never increases.

If I didn't have a Rak v1, I would have just reflashed and upgrade to another 64Gb card (and wipe out the dbs in the process)... unfortunately, this isn't possible because of the security/onboarding key... unless someone can tell me where this is and how i can recreate it onto a new (non-cloned) SD card.

**Comment by m1xmstr** [comment]
> 

Since you are on a v1 can you try cloning your original card to a 64GB high/max endurance card and see if that works?  That is what I would try to rule out a storage issue.

**Comment by cuteogre** [comment]
I already did.. cloned my original 32gb SD card onto a 64gb high endurance sandisk card (so it only has 32gb still) and let that run in my miner ... it's been 2 days now and still the same problem.

**Comment by m1xmstr** [comment]
> I already did.. cloned my original 32gb SD card onto a 64gb high endurance sandisk card (so it only has 32gb still) and let that run in my miner ... it's been 2 days now and still the same problem.
> 
> Note that I never had any problems with my original 32gb card.. no disk errors/green lights. And when I cloned it, no issues with the read.

On RAKstars "jmarcelino" noted that the new card will get partitioned on the first boot and make use of the remaining space.  Another user also confirmed this to be the case.  

Other users are reporting success after rebooting the miner again.  I would run a diagnostic and click "Send diagnostic to support" and note the current block you're on -- then perform it again in a couple hours.  If there is movement you might just have to wait it out.  There should be a new OTA coming in the next day or two according to their discord.

**Comment by m1xmstr** [comment]
After going offline again for 3 days another power cycle brought back the miner ping -- within 30 mins the miner created a challenge -- The devs on Helium Discord said they will be pushing a new image Monday (today) or Tuesday to help address these issues: https://discord.com/channels/404106811252408320/730418759298318346

After a power cycle this changed to working again (15 mins after):
<img width="747" alt="image" src="https://user-images.githubusercontent.com/4117245/150821250-ecfe5236-23d5-43a5-9d6c-30d72ba7d72f.png">

Where previously after day 2 the status for the miner was 0/0

**Comment by meowshka** [comment]
@m1xmstr I'm sorry it took a while to get back to you. Looks like your hotspot bent-merlot-boar is working fine right now. If you have any other issues with it, please contact the manufacturer directly. Here's their discord: https://discord.com/invite/gae6cGa7jn
