### ISSUE TITLE
What if assert is not in position?

### ISSUE THREAD

**Issue by marenshuai** [helium/miner#1369]
assert failed 
![1642605843(1)](https://user-images.githubusercontent.com/48117013/150161108-d6120071-c953-4dff-818c-1ac169f78611.png)
![image](https://user-images.githubusercontent.com/48117013/150161340-bf8dd03f-4fab-452a-a17a-0cfbe5b5ac75.png)
helium-wallet -f wallet.key hotspots assert --gateway 112ftvqBcvzaJM4SKuX8bRBNmbJnH2BmbE6VnQpscPHKraG7r  --lat 29.14167 --lon 106.8476 --mode full
The hotspots ID has been modified and is not a real ID！

What's the problem？

**Comment by meowshka** [comment]
@marenshuai I'm sorry it took a while to get back to you. I assume this issue is not relevant anymore, so closing this task. If you have any other problems, please feel free to ask in the Discussions section https://github.com/helium/miner/discussions or in our discord: https://discord.com/invite/helium
