### ISSUE TITLE
Hotspot Report - Multiple Miner Issues

### ISSUE THREAD

**Issue by tathatvamasi** [helium/miner#1445]
Hello! So, I've got 6 miners that are acting strange. They fluctuate between reporting online/offline, although whenever I ping them on hotspotty, they report online, and connected. They're doing no PoC. Only data packet transfer on occasion. From everything I can tell on my end they're set up correctly, high locations, ethernet, not relayed, etc, I'm not sure why they're performing the way they are. All of them were performing great previously. If anyone could take a look at these hotspots and give me some insight it would be greatly appreciated.

Striped Hotpink Monkey
Sparkley Felt Giraffe
Funny Grape Llama
Shambolic Hemp Ape
Furry Sage Panther
Modern Taupe Newt

Thank you!

**Comment by Hromec84** [comment]
My  two miner is acting strange.
My friends miner's are acting strange.
Helium ??????????

**Comment by mojomartini** [comment]
> My two miner is acting strange. My friends miner's are acting strange. Helium ??????????

I hope you're not expecting to get help based just on that information.

**Comment by Raimis707** [comment]
i have been writing to everyone for almost a month that the sensecap from 01.24 has stopped witnessing and broadcasting and no one is helping.  so the information he wrote enough because no one solves the problems anyway

**Comment by serbyxp** [comment]
I don’t work for helium or am I associated with any manufacture. But I have mentioned in almost every post something about this. Helium themselves have only made the statement about the miners being “relayed” if your relayed your not going to earn. If you are not relayed and you have a firewall on your network that’s blocking that connection your not going to be able to connect to anyone. What I mean by firewall is anything on your network VPN , traffic filters , proxies , even if you have forwarded port TCP/44158 you still going to have to look into your router settings and make sure it’s both inbound and outbound on TCP and look in your filter settings advanced settings in your router, you may have the port open but it could be filtering p2p . Beyond that, your manufacture is responsible for updating your hardware. 

If other hotspots from the same manufacture you have is having the same problems across the board, then your manufacture needs to fix their hardware firmware issues. 

Currently as of writing this has your situation gotten cleared up ? A lot of different updates have happened. 

You still have warranty on your miner ? I would talk to them and find out. Because you might have broken hardware somewhere along the line, maybe you didn’t plug the antenna in when you turned it on, or used a connector that wasn’t properly matched to the radio or your hardware, and fried a part of your radio, network adapter , … 

maybe if you bought aftermarket parts like antena could be broken. You need to go down the list of things. If you mounted it on your roof, did a bird come and knock it over or peck at the cable…

**Comment by florian-asche** [comment]
Does the miners internet disconnect after 24hrs?

**Comment by meowshka** [comment]
@tathatvamasi please reach out to the manufacturer of your hotspots directly regarding this issue. Here's their discord: https://discord.com/invite/gae6cGa7jn
