### ISSUE TITLE
Miner info --blocks-behind

### ISSUE THREAD

**Issue by mjohngreene** [helium/miner#458]
I have no idea how difficult it would be to implement but it might be handy to show the delta between the miner's and the chain's respective "heights."  Presuming such functionality is not already readily available, of course.  Unfortunately, I lack the coding chops to tackle this and submit a PR.

**Comment by evanmcc** [comment]
I'm not sure that this is an appropriate feature for the miner itself at the current moment.  For various theoretical reasons, it's difficult for the miner to determine where the ultimate chain height is with any certainty, other than by syncing all available blocks.  

In the end, this would just amount to an API call to known synced hosts, which, I feel, doesn't have a strong reason to live in the miner itself.  I'm open to being convinced otherwise, but absent such persuasion, I'll close this issue in a day or two.

**Comment by mjohngreene** [comment]
Makes sense, @evanmcc.  I'd thought (hoped?) it might be a matter of just presenting info that was basically readily available.  Guess not.  

Feel free to close whenever you see fit.

**Comment by vihu** [comment]
> it might be a matter of just presenting info that was basically readily available

Unfortunately no, a local miner doesn't really have any idea about what the latest current chain height would be (hence it goes into sync mode and waits for blocks to get gossiped to it)
