### ISSUE TITLE
Which Helium miner meets the frequency code for Ghana EU433

### ISSUE THREAD

**Issue by iplusq** [helium/miner#760]
I want to mine HNT in Ghana. Which miner meets my country frequency of EU433 (according to: https://github.com/helium/miner/blob/master/priv/countries_reg_domains.csv?fbclid=IwAR0ahvKzCJvncYK-cyDhKAmGA_kEuxe8WF5jX61qUxevwAaBmyh2311IApw#L83).

**Comment by shawaj** [comment]
I don't believe any current vendors support EU433

**Comment by Sikani1** [comment]
@shawaj @iplusq @vihu I noticed from the helium explorer that all hotspots in Nigeria, Kenya and Senegal have frequency plans of EU868. Since from the https://github.com/helium/miner/blob/master/priv/countries_reg_domains.csv?fbclid=IwAR0ahvKzCJvncYK-cyDhKAmGA_kEuxe8WF5jX61qUxevwAaBmyh2311IApw#L83 Ghana has frequency EU433, and no known model of that kind has been released, Is it possible/probable that EU868 as used in Nigeria which is 2 countries away from Ghana can be successfully deployed in Ghana? I have seen about 5 distantly isolated HEX in Ghana, I don't know how they are faring and wish I could contact them. Can anyone help with the idea I just presented?
