### ISSUE TITLE
What is considered synced?

### ISSUE THREAD

**Issue by shawaj** [helium/miner#957]
On explorer it seems that anything within 1500 blocks is considered synced https://github.com/helium/explorer/blob/d558450bbb581d4b5aa2331ed5a5de6c3eb69ff5/components/Hotspots/utils.js#L6

However, IIRC this is just for the purposes of estimation for the explorer? 

What does the miner actually consider as synced for the purposes of earning HNT? I saw 90 blocks for `poc_challenge_sync_interval` in https://github.com/helium/miner/blob/8906ca280544d9d14ce34fade54ea6f5e51e5c98/audit/var-5.md

But just wanted to check if that's still accurate?

**Comment by evanmcc** [comment]
@PharkMillups is there a section of the docs that addresses this?  If so, I'd like to move the issue there.

**Comment by shawaj** [comment]
@evanmcc I couldn't see one, but if you have more details on the answer, I'd be happy to do a PR on the docs repo

**Comment by evanmcc** [comment]
Essentialy, you're synced enough to earn if you're close enough to submit poc requests before they're too old, and will earn more if you're synced enough to get and process requests to you before they time out.  You'll also need to be synced enough to know who the current consensus group is so that you can submit transactions.  Typically this will mean you need to be within maybe 250 blocks of the newest block, but it's not impossible to be a little farther back and still be able to make things happen.
